### ISSUE TITLE
gwt-gradle-plugin uses deprecated api by Gradle 4.0

### ISSUE THREAD

**Issue by milesbennetdyson4** [steffenschaefer/gwt-gradle-plugin#114]
After adding this plugin to project and running it with Gradle 4.0 I get `Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0` warning message. This line is responsible for it https://github.com/steffenschaefer/gwt-gradle-plugin/blob/master/gwt-gradle-plugin/src/main/java/de/richsource/gradle/plugins/gwt/GwtBasePlugin.java#L272.

**Comment by sriharshachilakapati** [comment]
Update the version of the library. Change it to 1.0.1-SNAPSHOT or
something. I'll check it out what the latest it soon.

**Comment by sriharshachilakapati** [comment]
This plugin is now not maintained. Please switch to this fork which is up to date: https://github.com/jiakuan/gwt-gradle-plugin

Use the version 1.0.3 instead.

**Comment by milesbennetdyson4** [comment]
Great, it looks like switching it to that plugin solved my problem.
