### ISSUE TITLE
Debug options

### ISSUE THREAD

**Issue by hrstoyanov** [steffenschaefer/gwt-gradle-plugin#31]
Steffen,
In your excellent plugin&docs you suggest that one could run dev mode with the below options but has to  wait until the IDE attaches to the dev process on the debug port:
 ./gradlew -DgwtDev.debug=true ....

How can one, however, run in debug mode with these  JVM setting instead:
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

The difference is that with this dev mode will launch and not wait, the developer is free to attach /detach debugger to it at will. Also, how can one specify different port than 5005?

Thanks.

**Comment by nskmda** [comment]
Steffen, looks like your solution doesn't work.
I tried to use it but I get 

:gwtDev
Error occurred during initialization of VM
agent library failed to init: jdwp
ERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.
:gwtDev FAILED


And when I tried to configure the same port to run Gradle itself, I got the following:

:gwtDevERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.

Error occurred during initialization of VM
agent library failed to init: jdwp
:gwtDev FAILED
