### ISSUE TITLE
compileGwt when build.gradle is located in a different project

### ISSUE THREAD

**Issue by wtfguy** [steffenschaefer/gwt-gradle-plugin#43]
I have 2 projects  org.sample.project and org.sample.project.client.

The build.gradle file sits in org.sample.project and the gwtModule is org.sample.project.client

How do i update the classpath to declare the source of the the other project.
When i use:
modules 'org.sample.project.client.ProjectWebApp'
the gwt.xml file is not found.

When i try to to use it this way:
modules '../org.sample.project.client/src/org.sample.project.client.ProjectWebApp'
it says invalid module name.

What else can i do? Btw. i want to migrate an old project so i do not have a maven like structure.

**Comment by shabunc** [comment]
Is it still a case?
I should add that  adding project(':example-library').sourceSets.main.allJava.srcDirs
quite often won't be enough  - example libary is not necessarily evaluated up to the moment gwt declaration is evaluated.

that said, one need to add evaluationDependsOn(':example-library') as well.

That's well, seems non-optimal to me.
