### ISSUE TITLE
snapshot builds?

### ISSUE THREAD

**Issue by dodgex** [steffenschaefer/gwt-gradle-plugin#60]
Are there snapshot builds?

i'd like to use gwt 2.7.0-rc1 with jsinterop but that does not seem to work with the current release build. but as you added the new flags (mentioned in https://github.com/steffenschaefer/gwt-gradle-plugin/issues/55) i wonder if there are snapshot builds available somewhere.

thanks.

**Comment by confile** [comment]
Great @steffenschaefer you should add this to the doc I had the same problem.
