### ISSUE TITLE
Set style for gwt compiler

### ISSUE THREAD

**Issue by jozi-k** [steffenschaefer/gwt-gradle-plugin#79]
I am not able to set style for gwt compiler. I tried 

gwt {
  compiler { style = 'PRETTY'}
}

and then run war(Template) but with no success. Did I do something wrong?

**Comment by steffenschaefer** [comment]
Your code looks good. It works for me this way. So I guess, the problem is caused by something else.  Can you provide some more details on what is going on?

**Comment by jozi-k** [comment]
It works now, I just needed to delete war directory to see recompiled changes.
