### ISSUE TITLE
Integration with GWT Eclipse Plugin

### ISSUE THREAD

**Issue by joelhandwell** [steffenschaefer/gwt-gradle-plugin#83]
Recently GWT Eclipse Plugin got open sourced here https://github.com/gwt-eclipse-plugin/gwt-eclipse-plugin
Would integration with GWT Eclipse Plugin be a consideration?

**Comment by branflake2267** [comment]
I'm gearing up to add Gradle support to the GWT Eclipse plugin. I suspect this means a import and update configurator to start with to wire up the GWT nature and facet. Anything I should be aware of that you might find useful? 

https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/182

**Comment by joelhandwell** [comment]
@branflake2267 " a import and update configurator to start with to wire up the GWT nature and facet." That's the thing I exactly expect. Thank you for taking this consideration!
