### ISSUE TITLE
Is there a way to disable warTemplate task??

### ISSUE THREAD

**Issue by muten84** [steffenschaefer/gwt-gradle-plugin#93]
Hi, when i refresh my project with the eclipse task it will trigger every time a warTemplate task. I don't need thies behavior because i use tomcat-run plugin that points directly to the src/main/webapp folder. Is there a way to skip or disable the warTemplate task or simply to launch warTemplate manually only?

This happens everytime i run the following sequence of tasks:

[sts] -----------------------------------------------------
[sts] Starting Gradle build for the following tasks: 
[sts]      :cleanEclipse
[sts]      :eclipse
[sts] -----------------------------------------------------

Thanks in advance for all.

Luigi

**Comment by ghost** [comment]
I'm looking for an answer to this too.

**Comment by steffenschaefer** [comment]
try:

```
tasks.eclipse.dependsOn().remove(tasks.warTemplate)
```

after applying all plugins

**Comment by ghost** [comment]
Thanks Steffen

**Comment by gigibiffi84** [comment]
Hi it worked thanks
